#!/usr/bin/env bash

# Update the nginx configuration to run as nginx user 
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Restart nginx
service nginx restart

# Check if nginx is running as nginx user using pgrep
if pgrep -u nginx nginx &> /dev/null; then
    echo "Nginx is running as nginx user."
else
    echo "Nginx is not running as nginx user."
fi

# Checking that nginx is running on port 8080
nc -z 0 8080
